isEnabled: true
image:
  preset: node
build:
  command: npm install
run:
  command: npm start
  envs:
    - name: GITHUB_ACCESS_TOKEN
      value: 'sm://{{.projectId}}/github-access-token'
settings:
  type: service
  inSecure: true
  persistentVolume:
    size: 5
    mountPath: /home/app/data
