isEnabled: true
image:
  preset: node
build:
  command: npm install
run:
  command: npm start
settings:
  type: service
  inSecure: true
#  persistentVolume:
#    size: 5
#    mountPath: /home/app/data
